version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: '/var/www/html'
    depends_on:
      - composer
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - composer
    networks:
      - app-network
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: mailpit
    restart: unless-stopped
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_UI_PORT:-8025}:8025'
    networks:
      - app-network
  composer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: composer
    volumes:
      - .:/var/www/html
    command: composer install
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
